// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnMQKno7EKacnaXr2Ynz4_G985mwhTykY',
    appId: '1:787143493395:web:f49fe186fad162e19afce6',
    messagingSenderId: '787143493395',
    projectId: 'tickets-moviles',
    authDomain: 'tickets-moviles.firebaseapp.com',
    storageBucket: 'tickets-moviles.firebasestorage.app',
    measurementId: 'G-3HHFX9G0C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_IT7OZ-cdI6XO_9L3NZsIfiK8S6PfzM',
    appId: '1:787143493395:android:0933e8d9c7806a6e9afce6',
    messagingSenderId: '787143493395',
    projectId: 'tickets-moviles',
    storageBucket: 'tickets-moviles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMod26lFoqonmTzz6Vv0XQQN5mLAeL0q8',
    appId: '1:787143493395:ios:b6acb2c1542ffa7b9afce6',
    messagingSenderId: '787143493395',
    projectId: 'tickets-moviles',
    storageBucket: 'tickets-moviles.firebasestorage.app',
    iosBundleId: 'com.example.proyectoMoviles2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMod26lFoqonmTzz6Vv0XQQN5mLAeL0q8',
    appId: '1:787143493395:ios:b6acb2c1542ffa7b9afce6',
    messagingSenderId: '787143493395',
    projectId: 'tickets-moviles',
    storageBucket: 'tickets-moviles.firebasestorage.app',
    iosBundleId: 'com.example.proyectoMoviles2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnMQKno7EKacnaXr2Ynz4_G985mwhTykY',
    appId: '1:787143493395:web:77489037809443d29afce6',
    messagingSenderId: '787143493395',
    projectId: 'tickets-moviles',
    authDomain: 'tickets-moviles.firebaseapp.com',
    storageBucket: 'tickets-moviles.firebasestorage.app',
    measurementId: 'G-S5WD5KTNCP',
  );
}
